name: 'weather_project'
version: '1.0.0'
config-version: 2

profile: 'weather_project'
model-paths: ["models"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_project:
    staging:
      +materialized: view
      +schema: STAGING
    mart:
      +materialized: table
      +schema: MART