name: 'weather_project'
version: '1.0.0'
config-version: 2
profile: 'weather_project'
model-paths: ["models"]
snapshot-paths: ["snapshots"]
target-path: "target"
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_project:
    staging:
      +materialized: view
      +schema: STAGING
    mart:
      +materialized: table
      +schema: MART

snapshots:
  weather_project:
    +target_schema: MART