version: 2

models:
  - name: mart_weather
    description: "Daily aggregated weather summary per city - keeps full history"
    columns:
      - name: CITY_NAME
        description: "City name"
        tests:
          - not_null

      - name: COUNTRY
        description: "Country name"
        tests:
          - not_null

      - name: LOAD_DATE
        description: "Date the data was loaded"
        tests:
          - not_null

      - name: AVG_TEMP_C
        description: "Average temperature for the week forecast"
        tests:
          - not_null

      - name: WEEK_HIGH_C
        description: "Highest temperature in the forecast"
        tests:
          - not_null

      - name: WEEK_LOW_C
        description: "Lowest temperature in the forecast"
        tests:
          - not_null

      - name: TOTAL_PRECIPITATION_MM
        description: "Total rainfall in the forecast"
        tests:
          - not_null

      - name: RAINY_DAYS
        description: "Number of rainy days in the forecast"
        tests:
          - not_null

      - name: DAYS_FORECASTED
        description: "Number of days forecasted"
        tests:
          - not_null

      - name: WEEK_TEMP_CATEGORY
        description: "Temperature category"
        tests:
          - not_null
          - accepted_values:
              values: ['Very Hot', 'Hot', 'Warm', 'Comfortable', 'Cool', 'Cold']