-- Create the database
CREATE DATABASE IF NOT EXISTS WEATHER_DB;

-- Create three schemas (folders)
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.MART;

-- Create the compute warehouse
CREATE WAREHOUSE IF NOT EXISTS WEATHER_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse for the weather pipeline project';

-- Create the raw table
USE DATABASE WEATHER_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS WEATHER_RAW (
    LOAD_DATE        DATE,
    CITY_NAME        VARCHAR(100),
    COUNTRY          VARCHAR(100),
    LATITUDE         FLOAT,
    LONGITUDE        FLOAT,
    WEATHER_DATE     DATE,
    TEMP_MAX         FLOAT,
    TEMP_MIN         FLOAT,
    PRECIPITATION    FLOAT,
    INSERTED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Confirm
SHOW TABLES IN WEATHER_DB.RAW;